### ISSUE TITLE
Default V key using camera menu error

### ISSUE THREAD

**Issue by 1405100494** [Kyokaz/Kyokaz-s-Toolbox#1]
Hi!
shift v can be used normally, but pressing the V key will still report an error.
Thanks!

Python: Traceback (most recent call last):
  File "C:\Users\D\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\collection_manager\qcd_move_widget.py", line 517, in invoke
    allocate_main_ui(self, context)
  File "C:\Users\D\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\collection_manager\qcd_move_widget.py", line 744, in allocate_main_ui
    get_buttons(button_row_1_a, 1)
  File "C:\Users\D\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\collection_manager\qcd_move_widget.py", line 678, in get_buttons
    qcd_laycol = internals.layer_collections[qcd_slot_name]["ptr"]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'Cameras'

**Comment by 1405100494** [comment]
I seem to have misread this, which seems to be caused by the collection plugin.

**Comment by Kyokaz** [comment]
Seems like you're using Collection Manager addon which I haven't tried yet, if you think this is a direct issue when using my addon and the issue still persists, do let me know. 

I will look into Collection Manager in the mean time and see if I can figure something out, thanks!

**Comment by Kyokaz** [comment]
Closed due to a possible addon conflict with Collection Manager, will look into this and (if possible) be fixed in the next update.
